FileVersion = 1

[Project]
Name = "stb_rect_pack"
DefaultNamespace = "stb_rectpack"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_rect_pack_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_rect_pack.lib"]
