FileVersion = 1

[Project]
Name = "stb_rect_pack"
TargetType = "BeefLib"
StartupObject = "stb_rectpack.Program"
DefaultNamespace = "stb_rectpack"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\stb_rect_pack-windows.lib"]
