FileVersion = 1

[Project]
Name = "stb_image_write"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_image_write_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_image_write.lib"]
