FileVersion = 1

[Project]
Name = "stb_image_write"
TargetType = "BeefLib"
StartupObject = "stb_image_write.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/libs/stb_image_write-windows.lib"]
