FileVersion = 1

[Project]
Name = "stb_image_resize2"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_image_resize2_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_image_resize2.lib"]
