FileVersion = 1

[Project]
Name = "stb_vorbis"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_vorbis_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\stb_vorbis.lib"]
